spring:
  datasource:
    url: jdbc:h2:mem:diarydb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

  config:
    import: "classpath:/questionnaires/"